config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :news_items
  resources :tours
  resources :point_of_interests
  resources :events
  resources :waste_calendar do
    collection do
      get :import
      post :create_location
      get :edit_location
      get :remove_location
      post :create_tour
      get :edit_tour
      get :remove_tour
      get :tour_dates
      post :update_tour_dates
      post :create_street_tour_matrix
    end
  end
  resources :jobs
  resources :offers
  resources :constructions
  resources :surveys
  get "/surveys/:survey_id/comments", to: "survey_comments#index", as: :survey_comments
  resources :push_notifications, only: [:new, :create]
  resources :encounters_supports, only: [:index, :show]
  post "/encounters_supports/validate", to: "encounters_supports#validate"
  get "/encounters_supports/:id/verify/:user_id", to: "encounters_supports#verify_user", as: :encounters_supports_verify_user
  get "/data_provider", to: "data_provider#edit"
  get "/visibility/:item_type/:id/:visible", to: "data_provider#visibility"
  get "/visibility/:item_type/:id/:visible/:parent_id", to: "data_provider#visibility"
  patch "/data_provider", to: "data_provider#update"
  match "/login", to: "session#create", as: :log_in, via: %i[get post]
  get "/logout", to: "session#destroy"
  get "dashboard/index"
  resources :static_contents, except: :destroy, param: :name
  delete "/static_contents/:id", to: "static_contents#destroy"
  resources :deadlines
  resources :noticeboards, only: %i[index destroy]
  resources :defect_reports, only: %i[index destroy]

  get "/minio/signed_url", to: "minio#signed_url"

  get "*not_found", to: "application#not_found_404", status: 404

  root "dashboard#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/defect_reports_controller.rb
# frozen_string_literal: true

class DefectReportsController < ApplicationController
  before_action :verify_current_user
  before_action { verify_current_user_role("role_defect_report") }
  before_action :init_graphql_client

  def index
    results = @smart_village.query <<~GRAPHQL
      query {
        genericItems(genericType: "DefectReport") {
          id
          categories {
            name
            contact {
              email
            }
          }
          contentBlocks {
            title
            body
          }
          contacts {
            email
            firstName
            phone
          }
          mediaContents {
            sourceUrl {
              url
            }
          }
          addresses {
            street
            zip
            city
            geoLocation {
              latitude
              longitude
            }
          }
          dataProvider {
            name
          }
          updatedAt
          createdAt
          visible
        }
      }
    GRAPHQL

    @defect_reports = results.data.generic_items
  end

  def destroy
    results = @smart_village.query <<~GRAPHQL
      mutation {
        destroyRecord(
          id: #{params["id"]},
          recordType: "GenericItem"
        ) {
          id
          status
          statusCode
        }
      }
    GRAPHQL

    flash["notice"] = if results.try(:data).try(:destroy_record).try(:status_code) == 200
                        "Eintrag wurde gelöscht"
                      else
                        "Fehler: #{results.errors.inspect}"
                      end
    redirect_to defect_reports_path
  end
end

app/views/defect_reports/_modal_content.html.erb
<div class="modal fade" id="content_<%= defect_report.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div>
          <strong><%= defect_report.categories.first.try(:name) %></strong>
          <h5 class="modal-title" id="exampleModalLabel">
            <%= defect_report.content_blocks.first.try(:title) %>
          </h5>
        </div>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <%= defect_report.content_blocks.first.try(:body) %>

        <% image_url = defect_report.media_contents.first.try(:source_url).try(:url) %>

        <% if image_url %>
          <%= image_tag(image_url, class: "mt-3") %>
        <% end %>

        <% address = defect_report.addresses.try(:first) %>

        <% if address.present? %>
          <% street = address.street %>
          <% zip = address.zip %>
          <% city = address.city %>

          <div class="row">
            <div class="col mt-3">
              <%= "Adresse: #{street}, #{zip} #{city}" if street && zip && city %>

              <%= hidden_field_tag "#{defect_report.id}-geo_location_latitude", address.try(:geo_location).try(:latitude) %>
              <%= hidden_field_tag "#{defect_report.id}-geo_location_longitude", address.try(:geo_location).try(:longitude) %>
              <div id="leafletMap-<%= defect_report.id %>" class="leafletMap" data-map-click="false" data-map-in-modal="true"></div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <div class="mr-auto">
          Name: <%= defect_report.contacts.first.try(:first_name) %>
          <br />
          E-Mail:
          <a
            href="mailto:<%= defect_report.contacts.first.try(:email) %>"
            title="mail to <%= defect_report.contacts.first.try(:email) %>"
            target="_blank"
          >
            <%= defect_report.contacts.first.try(:email) %>
          </a>
          <br />
          Telefon: <%= defect_report.contacts.first.try(:phone) %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $('[data-target="#content_<%= defect_report.id %>"]').on('click', function() {
    setTimeout(() => {
      window.map['leafletMap-<%= defect_report.id %>'].invalidateSize();
    }, 500);
  });
</script>

app/views/defect_reports/index.html.erb
<div class="d-flex flex-wrap align-items-center row-gap justify-content-between mb-5">
  <h1 class="h3 mb-0 pb-0 font-weight-bold mr-3">Mängelmelder</h1>
</div>

<div class="table-responsive pb-4">
  <table class="table data_table bg-white">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Titel</th>
        <th scope="col" class="nosort">Inhalt</th>
        <th scope="col">Kategorie</th>
        <th scope="col">Änderungsdatum</th>
        <th scope="col">Erstellungsdatum</th>
        <% if editor? || extended_user? %>
          <th>Datenquelle</th>
        <% end %>
        <% if editor? %>
          <th scope="col" class="nosort">Sichtbarkeit</th>
        <% end %>
        <th scope="col" class="nosort">Aktionen</th>
      </tr>
    </thead>
    <tbody>
      <% @defect_reports.each do |defect_report| %>
        <tr>
          <th scope="row"><%= defect_report.id %></th>
          <td>
            <%= defect_report.content_blocks.first.try(:title) || "" %>
          </td>
          <td>
            <%= link_to(
                  (defect_report.content_blocks.first.try(:body) || "").truncate(30),
                  "#",
                  data: { toggle: "modal", target: "#content_#{defect_report.id}" }
                ) %>
            <%= render(
                  partial: "defect_reports/modal_content",
                  locals: { defect_report: defect_report }
                ) %>
          </td>
          <td><%= defect_report.categories.first.try(:name) || "" %></td>
          <td data-sort="<%= DateTime.parse(defect_report.updated_at).to_i %>">
            <%= to_local_date_time(defect_report.updated_at) %>
          </td>
          <td data-sort="<%= DateTime.parse(defect_report.created_at).to_i %>">
            <%= to_local_date_time(defect_report.created_at) %>
          </td>
          <% if editor? || extended_user? %>
            <td><%= defect_report.data_provider.try(:name) %></td>
          <% end %>
          <% if editor? %>
            <td align="center"><%= visibility_switch(defect_report, "defect_report") %></td>
          <% end %>
          <td align="right" class="text-nowrap">
            <%= link_to defect_report_path(defect_report.id), method: :delete, "data-confirm" => "Diesen Eintrag wirklich löschen?", class: "btn btn-sm btn-danger", title: "Löschen" do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>